### ISSUE TITLE
Настройка окружения

### ISSUE THREAD

**Issue by ruslansenatorov** [SENATOROVAI/DataScience-Zagir#2]
https://github.com/SENATOROVAI/DataScience-Zagir/blob/d99d2aeb3dbc83d52964ea11464ccb6e445c40b4/hw.txt#L1-L51

**Comment by zagir-dg** [comment]
### Прогресс выполнения

- [x] Задание 1: Скачал репозиторий и открыл в VS Code
- [x] Задание 2: Установил pre-commit
- [x] Задание 3: Настроил линтеры
- [x] Задание 4: Установил все необходимые плагины
- [x] Задание 5: Повторил материалы по ссылке
